### ISSUE TITLE
add color, change date format in letter.tex

### ISSUE THREAD

**Issue by TheRojam** [cmichi/latex-template-collection#2]
I like to add some color *header-section* and like to change the date format.
and may add a picture to signature.

**Comment by cmichi** [comment]
Hi there, you can easily change some colors around by using e.g. the LaTeX [color packages](https://en.wikibooks.org/wiki/LaTeX/Colors). 

In terms of date format: Some template use the babel package which influences the output of the `\today` command, if you change the `german` (or `english`) option of babel to something else this might already yield the result you are looking for.

In terms of picture in the signature: Try replacing your textual signature with a figure command. So something like:
```
\usepackage{float}

…

\begin{figure}[H]
  \centering
  \includegraphics{your-signature.png}
\end{figure}
```

If this doesn't help you feel free to open a feature request (but please state which template you are referring to).
